
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class TokenNames {
  /* terminals */
  public static final int TIMES = 8;
  public static final int RBRACK = 14;
  public static final int ONEPLUS = 3;
  public static final int LT = 25;
  public static final int CLASS = 19;
  public static final int SEMICOLON = 17;
  public static final int BIG_INT = 32;
  public static final int PLUS = 6;
  public static final int INT = 31;
  public static final int RBRACE = 16;
  public static final int RPAREN = 12;
  public static final int WHILE = 9;
  public static final int LBRACK = 13;
  public static final int RETURN = 23;
  public static final int DOll = 29;
  public static final int IF = 2;
  public static final int GT = 27;
  public static final int NIL = 22;
  public static final int LPAREN = 11;
  public static final int LBRACE = 15;
  public static final int ID = 33;
  public static final int STRING = 34;
  public static final int COMMA = 26;
  public static final int EOF = 0;
  public static final int DIVIDE = 10;
  public static final int MINUS = 7;
  public static final int DOT = 30;
  public static final int error = 1;
  public static final int ASSIGN = 18;
  public static final int EQ = 5;
  public static final int NEW = 24;
  public static final int EXTENDS = 20;
  public static final int ARRAY = 21;
  public static final int BINOP = 28;
  public static final int KLINI = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ONEPLUS",
  "KLINI",
  "EQ",
  "PLUS",
  "MINUS",
  "TIMES",
  "WHILE",
  "DIVIDE",
  "LPAREN",
  "RPAREN",
  "LBRACK",
  "RBRACK",
  "LBRACE",
  "RBRACE",
  "SEMICOLON",
  "ASSIGN",
  "CLASS",
  "EXTENDS",
  "ARRAY",
  "NIL",
  "RETURN",
  "NEW",
  "LT",
  "COMMA",
  "GT",
  "BINOP",
  "DOll",
  "DOT",
  "INT",
  "BIG_INT",
  "ID",
  "STRING"
  };
}

